/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FormsNewRouteImport } from './routes/forms.new'
import { Route as FormsFormIdIndexRouteImport } from './routes/forms.$formId.index'
import { Route as FormsFormIdResponsesRouteImport } from './routes/forms.$formId.responses'
import { Route as FormsFormIdEditRouteImport } from './routes/forms.$formId.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsNewRoute = FormsNewRouteImport.update({
  id: '/forms/new',
  path: '/forms/new',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsFormIdIndexRoute = FormsFormIdIndexRouteImport.update({
  id: '/forms/$formId/',
  path: '/forms/$formId/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsFormIdResponsesRoute = FormsFormIdResponsesRouteImport.update({
  id: '/forms/$formId/responses',
  path: '/forms/$formId/responses',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsFormIdEditRoute = FormsFormIdEditRouteImport.update({
  id: '/forms/$formId/edit',
  path: '/forms/$formId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/forms/new': typeof FormsNewRoute
  '/forms/$formId/edit': typeof FormsFormIdEditRoute
  '/forms/$formId/responses': typeof FormsFormIdResponsesRoute
  '/forms/$formId/': typeof FormsFormIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/forms/new': typeof FormsNewRoute
  '/forms/$formId/edit': typeof FormsFormIdEditRoute
  '/forms/$formId/responses': typeof FormsFormIdResponsesRoute
  '/forms/$formId': typeof FormsFormIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/forms/new': typeof FormsNewRoute
  '/forms/$formId/edit': typeof FormsFormIdEditRoute
  '/forms/$formId/responses': typeof FormsFormIdResponsesRoute
  '/forms/$formId/': typeof FormsFormIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/demo'
    | '/login'
    | '/signup'
    | '/forms/new'
    | '/forms/$formId/edit'
    | '/forms/$formId/responses'
    | '/forms/$formId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/demo'
    | '/login'
    | '/signup'
    | '/forms/new'
    | '/forms/$formId/edit'
    | '/forms/$formId/responses'
    | '/forms/$formId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/demo'
    | '/login'
    | '/signup'
    | '/forms/new'
    | '/forms/$formId/edit'
    | '/forms/$formId/responses'
    | '/forms/$formId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DemoRoute: typeof DemoRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  FormsNewRoute: typeof FormsNewRoute
  FormsFormIdEditRoute: typeof FormsFormIdEditRoute
  FormsFormIdResponsesRoute: typeof FormsFormIdResponsesRoute
  FormsFormIdIndexRoute: typeof FormsFormIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/new': {
      id: '/forms/new'
      path: '/forms/new'
      fullPath: '/forms/new'
      preLoaderRoute: typeof FormsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/$formId/': {
      id: '/forms/$formId/'
      path: '/forms/$formId'
      fullPath: '/forms/$formId/'
      preLoaderRoute: typeof FormsFormIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/$formId/responses': {
      id: '/forms/$formId/responses'
      path: '/forms/$formId/responses'
      fullPath: '/forms/$formId/responses'
      preLoaderRoute: typeof FormsFormIdResponsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/$formId/edit': {
      id: '/forms/$formId/edit'
      path: '/forms/$formId/edit'
      fullPath: '/forms/$formId/edit'
      preLoaderRoute: typeof FormsFormIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DemoRoute: DemoRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  FormsNewRoute: FormsNewRoute,
  FormsFormIdEditRoute: FormsFormIdEditRoute,
  FormsFormIdResponsesRoute: FormsFormIdResponsesRoute,
  FormsFormIdIndexRoute: FormsFormIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
