/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FormsFormIdRouteImport } from './routes/forms.$formId'
import { Route as FormsFormIdResponsesRouteImport } from './routes/forms.$formId.responses'
import { Route as FormsFormIdEditRouteImport } from './routes/forms.$formId.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsFormIdRoute = FormsFormIdRouteImport.update({
  id: '/forms/$formId',
  path: '/forms/$formId',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsFormIdResponsesRoute = FormsFormIdResponsesRouteImport.update({
  id: '/responses',
  path: '/responses',
  getParentRoute: () => FormsFormIdRoute,
} as any)
const FormsFormIdEditRoute = FormsFormIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => FormsFormIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/forms/$formId': typeof FormsFormIdRouteWithChildren
  '/forms/$formId/edit': typeof FormsFormIdEditRoute
  '/forms/$formId/responses': typeof FormsFormIdResponsesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/forms/$formId': typeof FormsFormIdRouteWithChildren
  '/forms/$formId/edit': typeof FormsFormIdEditRoute
  '/forms/$formId/responses': typeof FormsFormIdResponsesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/forms/$formId': typeof FormsFormIdRouteWithChildren
  '/forms/$formId/edit': typeof FormsFormIdEditRoute
  '/forms/$formId/responses': typeof FormsFormIdResponsesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/demo'
    | '/login'
    | '/signup'
    | '/forms/$formId'
    | '/forms/$formId/edit'
    | '/forms/$formId/responses'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/demo'
    | '/login'
    | '/signup'
    | '/forms/$formId'
    | '/forms/$formId/edit'
    | '/forms/$formId/responses'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/demo'
    | '/login'
    | '/signup'
    | '/forms/$formId'
    | '/forms/$formId/edit'
    | '/forms/$formId/responses'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DemoRoute: typeof DemoRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  FormsFormIdRoute: typeof FormsFormIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/$formId': {
      id: '/forms/$formId'
      path: '/forms/$formId'
      fullPath: '/forms/$formId'
      preLoaderRoute: typeof FormsFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/$formId/responses': {
      id: '/forms/$formId/responses'
      path: '/responses'
      fullPath: '/forms/$formId/responses'
      preLoaderRoute: typeof FormsFormIdResponsesRouteImport
      parentRoute: typeof FormsFormIdRoute
    }
    '/forms/$formId/edit': {
      id: '/forms/$formId/edit'
      path: '/edit'
      fullPath: '/forms/$formId/edit'
      preLoaderRoute: typeof FormsFormIdEditRouteImport
      parentRoute: typeof FormsFormIdRoute
    }
  }
}

interface FormsFormIdRouteChildren {
  FormsFormIdEditRoute: typeof FormsFormIdEditRoute
  FormsFormIdResponsesRoute: typeof FormsFormIdResponsesRoute
}

const FormsFormIdRouteChildren: FormsFormIdRouteChildren = {
  FormsFormIdEditRoute: FormsFormIdEditRoute,
  FormsFormIdResponsesRoute: FormsFormIdResponsesRoute,
}

const FormsFormIdRouteWithChildren = FormsFormIdRoute._addFileChildren(
  FormsFormIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DemoRoute: DemoRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  FormsFormIdRoute: FormsFormIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
